# shellcheck shell=bash
# lib/sudoers.sh — render, validate, and atomically activate per-agent sudoers.
# This is the enforcement core. Rules that must never be violated:
#   * validate with `visudo -cf` on a temp file BEFORE activating;
#   * the temp file starts with '.' so a crash mid-write leaves it INACTIVE
#     (sudo ignores dotfiles in sudoers.d);
#   * the final filename has NO dot (sudo ignores names containing '.');
#   * mode 0440 root:root; activation is a single atomic rename;
#   * the previous good file is kept for rollback.

[[ -n "${_LLM2SSH_SUDOERS_SOURCED:-}" ]] && return 0
_LLM2SSH_SUDOERS_SOURCED=1

sudoers_file() { printf '%s/llm2ssh-%s' "$LLM2SSH_SUDOERSD" "$1"; }

# sudoers_alias_name AGENT -> a valid Cmnd_Alias identifier (upper, _, digits).
sudoers_alias_name() {
  local up="${1^^}"          # uppercase
  up="${up//-/_}"            # hyphens -> underscores (invalid in aliases)
  printf 'LLM2SSH_%s' "$up"
}

# sudoers_render AGENT BASE EXPIRES  (reads P_* globals) -> content on stdout.
# BASE/EXPIRES are metadata only (comments). Assumes profile_load already ran.
sudoers_render() {
  local agent="$1" base="${2:-}" expires="${3:-never}"
  local alias; alias="$(sudoers_alias_name "$agent")"
  printf '# Managed by llm2ssh %s — DO NOT EDIT (regenerated by `llm2ssh grant`)\n' "$LLM2SSH_VERSION"
  printf '# agent: %s   profile: %s   base: %s\n' "$agent" "$P_NAME" "${base:-$P_NAME}"
  printf '# expires: %s\n' "$expires"
  printf 'Defaults:%s env_reset, !lecture\n' "$agent"
  printf 'Defaults:%s logfile=%s/sudo-%s.log\n' "$agent" "/var/log/llm2ssh" "$agent"
  if [[ "${P_SUDO_ALL:-0}" -eq 1 ]]; then
    printf '%s ALL=(ALL:ALL) NOPASSWD: ALL\n' "$agent"
    return 0
  fi
  # Cmnd_Alias with comma-separated members, backslash-continued.
  printf 'Cmnd_Alias %s = ' "$alias"
  local i n="${#P_SUDO[@]}"
  for ((i=0; i<n; i++)); do
    if [[ "$i" -eq 0 ]]; then
      printf '%s' "${P_SUDO[i]}"
    else
      printf ', \\\n    %s' "${P_SUDO[i]}"
    fi
  done
  printf '\n'
  printf '%s ALL=(root) NOPASSWD: %s\n' "$agent" "$alias"
}

# sudoers_validate FILE -> 0 if `visudo -cf` accepts it.
sudoers_validate() {
  local file="$1"
  have_cmd visudo || die "visudo not found (install the 'sudo' package)"
  visudo -cf "$file" >/dev/null 2>&1
}

# sudoers_activate AGENT  (content on stdin)
# Render -> hidden temp -> visudo -cf -> chmod 0440 -> atomic mv. Saves prev.
sudoers_activate() {
  local agent="$1"
  local final tmp prev
  final="$(sudoers_file "$agent")"
  tmp="$LLM2SSH_SUDOERSD/.llm2ssh-$agent.tmp.$$"
  prev="$(agent_dir "$agent")/sudoers.prev"
  ensure_dir "$LLM2SSH_SUDOERSD" 0755 "root:root"
  cat >"$tmp"
  chmod 0440 "$tmp"
  chown root:root "$tmp" 2>/dev/null || true
  if ! sudoers_validate "$tmp"; then
    rm -f "$tmp"
    die_validation "generated sudoers failed 'visudo -cf' — refusing to activate (old grant untouched)"
  fi
  # Save current good file for rollback before replacing.
  if [[ -f "$final" ]]; then
    ensure_dir "$(dirname "$prev")" 0700 "root:root"
    cp -a "$final" "$prev" 2>/dev/null || true
  fi
  mv -f "$tmp" "$final"
  # Whole-config sanity (may warn about pre-existing breakage elsewhere).
  if have_cmd visudo && ! visudo -c >/dev/null 2>&1; then
    warn "visudo -c reports a problem in the overall sudoers config (our file validated individually)"
  fi
}

# sudoers_remove AGENT — remove the agent's grant file (idempotent).
sudoers_remove() {
  local final; final="$(sudoers_file "$1")"
  rm -f "$final"
}

# sudoers_apply AGENT BASE EXPIRES — high-level: render P_* and activate,
# or remove the file when the profile grants no sudo.
sudoers_apply() {
  local agent="$1" base="${2:-}" expires="${3:-never}"
  if [[ "${P_SUDO_ALL:-0}" -ne 1 && "${#P_SUDO[@]}" -eq 0 ]]; then
    sudoers_remove "$agent"
    return 0
  fi
  sudoers_render "$agent" "$base" "$expires" | sudoers_activate "$agent"
}
